#!/bin/bash

pip install virtualenv
virtualenv env
. env/Scripts/activate
pip install -r requirements.txt
cd frontend/
npm install
npm install webpack
npm run dev
cd ..
python manage.py runserver 0.0.0.0:8000