# Generated by Django 3.0.5 on 2020-04-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=60)),
                ('href', models.CharField(max_length=300)),
            ],
        ),
    ]
