# Generated by Django 3.0.7 on 2020-06-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0003_linksmodel_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksmodel',
            name='search',
        ),
    ]
